### ISSUE TITLE
Why main.c have many header?

### ISSUE THREAD

**Issue by vjumpkung** [CPE35-Developer/-#5]
explain please .

**Comment by lazykern** [comment]
You don't understand

**Comment by namirinz** [comment]
### _It's do or die situation._

**Comment by namirinz** [comment]
Please review main.c again might be some bug. @Vjumpkung @hirasawaau @VeryHardBit @phusitsom @jiratQ

**Comment by namirinz** [comment]
nvm it's too good.

**Comment by lazykern** [comment]
no u

#include <assert.h>
#include <complex.h>
#include <ctype.h>
#include <errno.h>
#include <fenv.h>
#include <float.h>
#include <inttypes.h>
#include <iso646.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <signal.h>
#include <stdalign.h>
#include <stdarg.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include <string.h>
#include <tgmath.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>

is the best statement 

shut yo mouth

**Comment by AdroitBit** [comment]
As an `$ git clone` enjoyer. I think the contributions are trying to follow the repository's description 'ทำอะไรดี'.

This means they question like "Hunh.... Ok, What're we trying to do again?" during creating this repository.

Then they decide "Yeah,Let's spam every dependencies in existence which are installed by default anyway."

That is my theory for this question.
